import os
import sys
import logging
import requests
import yt_dlp
from telegram import Update
from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler, MessageHandler, filters

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', 
    level=logging.INFO
)
logger = logging.getLogger(__name__)

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
if not BOT_TOKEN:
    logger.critical("❌ DEPLOYMENT FAILED: Missing 'TELEGRAM_BOT_TOKEN' in Railway variables!")
    sys.exit(1)

BOT_TOKEN = BOT_TOKEN.strip().replace('"', '').replace("'", "")

# Function to fetch a live PO Token dynamically from an open-source solver API
def fetch_live_po_token():
    try:
        response = requests.get("https://yt-dlp.dev", timeout=5)
        if response.status_code == 200:
            data = response.json()
            po_token = data.get("po_token")
            visitor_data = data.get("visitor_data")
            logger.info("✅ Successfully fetched fresh live PO Token from remote solver engine.")
            return po_token, visitor_data
    except Exception as e:
        logger.error(f"⚠️ Dynamic token engine unreachable: {str(e)}. Using fallback client signatures.")
    return None, None

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👋 Send me any social media video link, and I will download it!")

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    url = update.message.text
    if not url.startswith("http"):
        await update.message.reply_text("❌ Please send a valid web link.")
        return

    logger.info(f"Processing URL: {url}")
    msg = await update.message.reply_text("📥 Processing video... Please wait.")

    filename = None
    
    # Universal fallback array for YouTube formats (Resolves YouTube Shorts compatibility)
    ydl_opts = {
        'format': 'bestvideo+bestaudio/best',  # Flexible format matching engine
        'outtmpl': '%(id)s.%(ext)s',
        'merge_output_format': 'mp4',
        'noplaylist': True,
        'quiet': True,
    }

    # Fetch live signature token before downloading
    po_token, visitor_data = fetch_live_po_token()
    
    if po_token and visitor_data:
        ydl_opts['extractor_args'] = {
            'youtube': {
                'po_token': f'web+{po_token}',
                'visitor_data': visitor_data,
                'player_client': ['web', 'default']
            }
        }
    else:
        ydl_opts['extractor_args'] = {
            'youtube': {
                'player_client': ['mweb', 'tv_embedded']
            }
        }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            filename = ydl.prepare_filename(info)

        # Handle extensions like .mkv or others generated by dynamic format selection
        if filename and not os.path.exists(filename):
            base, _ = os.path.splitext(filename)
            for ext in ['mp4', 'mkv', 'webm']:
                if os.path.exists(f"{base}.{ext}"):
                    filename = f"{base}.{ext}"
                    break

        if filename and os.path.exists(filename):
            with open(filename, 'rb') as video_file:
                await context.bot.send_video(
                    chat_id=update.effective_chat.id,
                    video=video_file,
                    caption="Here is your video! 🎬"
                )
            await msg.delete()
            logger.info("Video sent successfully.")
        else:
            raise FileNotFoundError("Target download file generation sequence failed.")

    except Exception as e:
        logger.error(f"Download processing failed: {str(e)}")
        await msg.edit_text(f"❌ Download failed.\n`{str(e)}`", parse_mode='Markdown')
    finally:
        if filename and os.path.exists(filename):
            os.remove(filename)

if __name__ == '__main__':
    logger.info("🤖 Starting Telegram Downloader Bot Application...")
    try:
        application = ApplicationBuilder().token(BOT_TOKEN).build()
        application.add_handler(CommandHandler("start", start))
        application.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))
        application.run_polling()
    except Exception as initialization_error:
        logger.critical(f"❌ Core engine crash during authorization setup: {str(initialization_error)}")
        sys.exit(1)
